
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { Sitecore } from "./_.Sitecore.Override"
import { CrossTraining } from "./Foundation.CrossTraining.model"
// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { ComponentRendering, RouteData, Field, ImageField, FileField, LinkField } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { DefaultComponentProps } from '@/lib/component-props';


export namespace CrossTraining.Banner.Fields {
    export type Banner = 
            CrossTraining.Base.Fields.Headline & 
            CrossTraining.Base.Fields.Description & { 
        fields?: { 
            /**
            * Represents the Background Color field (eaccab0a-4a50-44cf-8b9d-d9758ecefaea).
            */
            BackgroundColor: Field<string>;

            /**
            * Represents the Banner Image field (bcefbad7-0013-4e00-ae9f-e14beba2ff61).
            */
            Image: ImageField;

            /**
            * Represents the Primary CTA field (05e303df-1d7d-46ab-8ee2-98e4d74e438e).
            */
            PrimaryCTA: LinkField;

            /**
            * Represents the Primary CTA Text field (823a5f43-883d-4a3a-b3c1-97c3bd110461).
            */
            PrimaryCTAText: Field<string>;

            /**
            * Represents the Secondary CTA field (9b9a2fa5-59fb-48f5-addc-cd87cf477170).
            */
            SecondaryCTA: LinkField;

            /**
            * Represents the Secondary CTA Text field (53cfdc9d-c393-4026-bb93-0ce951980f74).
            */
            SecondaryCTAText: Field<string>;
 
        }
 }; 
}

export namespace CrossTraining.ContentBlock.Fields {
    export type ContentBlock = 
            CrossTraining.Base.Fields.Headline & 
            CrossTraining.Base.Fields.Description & { 
        fields?: {  
        }
 }; 
}

export namespace CrossTraining.Navigation.Header.Fields {
    export type Header = { 
        fields?: { 
            /**
            * Represents the Logo field (73ce6680-4193-457b-9a90-d12684227e70).
            */
            Logo: ImageField;

            /**
            * Represents the LogoLink field (681d74f7-8585-475f-93ab-9d57dbf26098).
            */
            LogoLink: LinkField;

            /**
            * Represents the NavigationLinks field (a8a06d9d-b646-473e-8fa7-48fe9d3423a1).
            */
            NavigationLinks: Sitecore.Override.ItemEx[];
 
        }
 }; 
}

export namespace CrossTraining.Navigation.Header.Fields {
    export type NavigationLink = { 
        fields?: { 
            /**
            * Represents the Link field (3b16d8f0-6433-4513-8647-5691d711ae08).
            */
            Link: LinkField;

            /**
            * Represents the SubNavigationLink field (863237e8-803a-4d07-9479-fb9e56140d45).
            */
            SubNavigationLink: Sitecore.Override.ItemEx[];

            /**
            * Represents the Title field (5305493c-31d2-4d9e-bdc4-2d45b433f79d).
            */
            Title: Field<string>;
 
        }
 }; 
}


